name: Documentation Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Documentation Structure
      run: |
        # Check for required documentation files
        echo "Checking for required documentation files..."
        for file in README.md docs/AGENT_RULES.md docs/AGENT_QUICK_REFERENCE.md docs/DIRECTORY_STRUCTURE.md; do
          if [ ! -f "$file" ]; then
            echo "Error: Required file $file is missing"
            exit 1
          fi
        done
        echo "All required documentation files are present."
        
        # Check for rules.json
        if [ ! -f "rules.json" ]; then
          echo "Error: Required file rules.json is missing"
          exit 1
        fi
        
        # Validate rules.json is valid JSON
        echo "Validating rules.json format..."
        if ! jq empty rules.json; then
          echo "Error: rules.json is not valid JSON"
          exit 1
        fi
        echo "rules.json is valid JSON."
        
        # Security check: Ensure there's no directory named '~' in the project root
        echo "Checking for security issues..."
        if [ -d "~" ]; then
          echo "Error: Security alert - Directory named '~' found in project root"
          echo "This could pose a security risk and should be removed"
          exit 1
        fi
        echo "No '~' directory found in project root."
        
        echo "Documentation structure validation completed successfully."
